# Generated by Django 5.1.1 on 2025-12-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_comment_count_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть публикацию.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Добавлено"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=256, verbose_name="Заголовок"),
                ),
                ("slug", models.SlugField(max_length=256, unique=True)),
                ("content", models.TextField(verbose_name="Содержимое")),
            ],
            options={
                "verbose_name": "статичная страница",
                "verbose_name_plural": "Статичные страницы",
            },
        ),
    ]
