# Generated by Django 5.1.1 on 2025-12-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="post",
            name="comment_count",
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Снимите галочку, чтобы скрыть публикацию",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Снимите галочку, чтобы скрыть публикацию",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Снимите галочку, чтобы скрыть публикацию",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Снимите галочку, чтобы скрыть публикацию",
                verbose_name="Опубликовано",
            ),
        ),
    ]
