# Generated by Django 5.1.1 on 2025-12-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_comment_is_published_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("created_at",),
                "verbose_name": "комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
